name: 'conventional-version-check'
description: 'read version content as conventional version'
inputs:
  sha-length:  # id of input
    description: 'length of short-sha to return'
    required: false
    default: '8'
  sha-short-variable-env:  # id of input
    description: 'short-sha env'
    required: false
    default: 'SHA-SHORT'
  tag-regex:
    description: 'Regex to capture a group text as tag name. Full tag string is returned if regex is not defined.'
    required: false
    default: ''
  tag-regex-group:
    description: 'Regex group number to return as tag name.'
    required: false
    default: '1'
  tag-version-env:  # id of input
    description: 'short-sha env'
    required: false
    default: 'GIT_TAG_VERSION'
  cc-log-path:
    description: "Path to the CHANGELOG file containing the log entries by conventional commits"
    required: false
    default: "./CHANGELOG.md"
  cc-version-wanted:
    description: "Version of the log entry wanted"
    required: false
outputs:
  sha: # output will be available to future steps
    description: 'commit of git full sha'
  short-sha:
    description: 'commit of git full sha short'
  tag-version:
    description: 'tag name when CI in refs/tags'
  cc-latest-version:
    description: 'version of latest conventional changelog'
  cc-latest-date:
    description: 'date of latest conventional changelog'
  cc-latest-status:
    description: 'status of latest'
  cc-latest-changes-log:
    description: 'content of latest conventional changelog'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  color: blue
  icon: tag